language: ruby
cache: bundler
env:
  - CPLUS_INCLUDE_PATH=/usr/include/atlas C_INCLUDE_PATH=/usr/include/atlas
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
before_install:
  - gem install bundler -v '~> 1.6'
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-base-dev
script: bundle exec rake compile && bundle exec rake spec
notifications:
  irc: "chat.freenode.net#sciruby"
